### ISSUE TITLE
award支持预渲染

### ISSUE THREAD

**Issue by zsedc800** [XimalayaCloud/award#26]
目前award缓存与预渲染只能渲染路由组件render后的结构，无法获取特定时刻渲染的快照结构
- award 单页使用时支持预渲染指定快照内容
- 服务端渲染缓存时能缓存指定的内容

**Comment by Topthinking** [comment]
@zsedc800 你是想渲染带有完整数据的页面么

如果这样子的话
- 服务端渲染的缓存势必比较重，一般都是通过varnish做一层静态缓存处理
- 单页的话，目前单页应用都是一个入口的index.html，如果里面塞一些内容的话，势必为出现屏幕内容闪烁的情况

**Comment by zsedc800** [comment]
- 首屏的内容比空白页来说不会增加太多
- 闪烁问题在于内容差异较大可以优化的
